//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Vuforia.SessionRecorderBehaviour.ShareRecordingEvent))]
	public class PropertyProvider_Vuforia_SessionRecorderBehaviour_ShareRecordingEvent : Unity.VisualScripting.SerializedPropertyProvider<Vuforia.SessionRecorderBehaviour.ShareRecordingEvent>
	{
	}
}
